name: dart_parser_helper
description: Dart parser helper is a wrapper over the Dart SDK analyzer parser
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  analyzer: any
  source_span: any
dev_dependencies:
  lints: ^2.0.0
